spring:
  profiles:
    include: db

  jwt:
    key: secret-key
    live:
      atk: 60000
      rtk: 300000

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG

