spring:
  profiles:
    include: db

  jwt:
    key: secret-key
    live:
      atk: 43200000
      rtk: 43200000

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG

